# Generated by Django 2.1.5 on 2019-01-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_auto_20190113_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsrecords',
            name='id',
        ),
        migrations.AlterField(
            model_name='newsrecords',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
